### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by salwinat0r** [samim23/polymath#21]
Tried running a local .mp3 file and it resulted in this error after `8/8 split stems` :

`Traceback (most recent call last):
  File "polymath.py", line 689, in <module>
    main()
  File "polymath.py", line 621, in main
    audio_features = get_audio_features(file=file,file_id=vid.id)  File "polymath.py", line 448, in get_audio_features
    stemsplit(file, 'htdemucs_6s')
  File "polymath.py", line 326, in stemsplit
    subprocess.run(["demucs", destination, "-n", demucsmodel]) #  '--mp3'
  File "C:\Users\salwy\miniconda3\envs\polymath\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\salwy\miniconda3\envs\polymath\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\salwy\miniconda3\envs\polymath\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by samim23** [comment]
Please try again, the last commit should likely fix this issue.

**Comment by lokmoe** [comment]
I am getting a somewhat same error:

`8/8 split stems
Traceback (most recent call last):
  File "C:\Users\Jannick\polymath\polymath.py", line 690, in <module>
    main()
  File "C:\Users\Jannick\polymath\polymath.py", line 622, in main
    audio_features = get_audio_features(file=file,file_id=vid.id)
  File "C:\Users\Jannick\polymath\polymath.py", line 449, in get_audio_features
    stemsplit(file, 'htdemucs_6s')
  File "C:\Users\Jannick\polymath\polymath.py", line 325, in stemsplit
    subprocess.run(["demucs", destination, "-n", demucsmodel]) #  '--mp3'
  File "C:\Users\Jannick\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Jannick\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Jannick\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Den angivne fil blev ikke fundet`
