### ISSUE TITLE
Error on Second stage (pitch tracking) 

### ISSUE THREAD

**Issue by Dimimiha** [samim23/polymath#25]
Windows 10

Tried running on a YouTube video.
This is the traceback:
`File "C:\Users\Dimi novo\polymath\polymath.py", line 690, in <module>
    main()
  File "C:\Users\Dimi novo\polymath\polymath.py", line 622, in main
    audio_features = get_audio_features(file=file,file_id=vid.id)
  File "C:\Users\Dimi novo\polymath\polymath.py", line 424, in get_audio_features
    frequency_frames = get_pitch_dnn(file)
  File "C:\Users\Dimi novo\polymath\polymath.py", line 317, in get_pitch_dnn
    time, frequency, confidence, activation = crepe.predict(audio, sr, model_capacity="tiny", viterbi=True, center=True, step_size=10, verbose=1) # tiny|small|medium|large|full
  File "C:\Users\Dimi novo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\crepe\core.py", line 255, in predict
    activation = get_activation(audio, sr, model_capacity=model_capacity,
  File "C:\Users\Dimi novo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\crepe\core.py", line 185, in get_activation
    model = build_and_load_model(model_capacity)
  File "C:\Users\Dimi novo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\crepe\core.py", line 44, in build_and_load_model
    from tensorflow.keras.layers import Input, Reshape, Conv2D, BatchNormalization
ModuleNotFoundError: No module named 'tensorflow'`

**Comment by samim23** [comment]
Make sure you have TensorFlow installed on your system! Will update the readme soon to cover this for windows systems

**Comment by Dimimiha** [comment]
I'm sorry, I'm such a newbie to this that I just took the readme completely at face value.
I'll come back to this later and follow the instructions.
Thank you for understanding.

**Comment by Dimimiha** [comment]
Okay, after installing TensorFlow, that stage went smoothly.
Now there's an error on 8/8 split steams stage.
`Traceback (most recent call last):
  File "C:\Users\Dimi novo\polymath\polymath.py", line 690, in <module>
    main()
  File "C:\Users\Dimi novo\polymath\polymath.py", line 622, in main
    audio_features = get_audio_features(file=file,file_id=vid.id)
  File "C:\Users\Dimi novo\polymath\polymath.py", line 449, in get_audio_features
    stemsplit(file, 'htdemucs_6s')
  File "C:\Users\Dimi novo\polymath\polymath.py", line 325, in stemsplit
    subprocess.run(["demucs", destination, "-n", demucsmodel]) #  '--mp3'
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by faradox** [comment]
@Dimimiha can you please provide the command you entered which produced your error? It looks like the file you specified to be added to the polymath library can not be found, possibly due to a spelling error in its path?

**Comment by Dimimiha** [comment]
I just tried to add a song from youtube.
`python polymath.py -a wNC9Njb5RME`
