### ISSUE TITLE
Documentation or requirements.txt incomplete: tensorflow

### ISSUE THREAD

**Issue by kjcole** [samim23/polymath#48]
Following the instructions in the README, I attempted to grab audio from YouTube. It downloaded okay but then:

```
2/8 pitch tracking
Traceback (most recent call last):
  File "/home/kjcole/gits/Audio/polymath/polymath.py", line 671, in <module>
    main()
  File "/home/kjcole/gits/Audio/polymath/polymath.py", line 618, in main
    audio_features = get_audio_features(file=file,file_id=vid.id)
  File "/home/kjcole/gits/Audio/polymath/polymath.py", line 395, in get_audio_features
    frequency_frames = get_pitch_dnn(file)
  File "/home/kjcole/gits/Audio/polymath/polymath.py", line 301, in get_pitch_dnn
    time, frequency, confidence, activation = crepe.predict(audio, sr, model_capacity="tiny", viterbi=True, center=True, step_size=10, verbose=1) # tiny|small|medium|large|full
  File "/home/kjcole/.local/lib/python3.10/site-packages/crepe/core.py", line 255, in predict
    activation = get_activation(audio, sr, model_capacity=model_capacity,
  File "/home/kjcole/.local/lib/python3.10/site-packages/crepe/core.py", line 185, in get_activation
    model = build_and_load_model(model_capacity)
  File "/home/kjcole/.local/lib/python3.10/site-packages/crepe/core.py", line 44, in build_and_load_model
    from tensorflow.keras.layers import Input, Reshape, Conv2D, BatchNormalization
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by kjcole** [comment]
Then I dd a `pip install tensorflow` reran `python polymath.py -a ...`  and got a core dump:

```
2/8 pitch tracking
2023-03-11 07:44:54.146851: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-11 07:44:54.287282: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/kjcole/.local/lib
2023-03-11 07:44:54.287303: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-11 07:44:54.921483: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/kjcole/.local/lib
2023-03-11 07:44:54.921599: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/kjcole/.local/lib
2023-03-11 07:44:54.921608: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-11 07:44:55.559438: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-03-11 07:44:55.559467: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (rama): /proc/driver/nvidia/version does not exist
2023-03-11 07:44:55.559733: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Aborted (core dumped)
```
