### ISSUE TITLE
Unable to scan MP3s on windows

### ISSUE THREAD

**Issue by jimmyeao** [samim23/polymath#53]
As for my environment,
im running in win 11, visual studio code, Python 3.10.7 (no virtual environment), ffmpeg is installed
this is the output I get trying to add a folder of MP3s (same issue if I try and add a single mp3 too):
```
PS F:\OneDrive\Documents\Github\polymath> python polymath.py -a H:/mp3s/beatport/
2023-03-29 16:14:53.934583: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-03-29 16:14:53.934915: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
---------------------------------------------------------------------------- 
--------------------------------- POLYMATH ---------------------------------
----------------------------------------------------------------------------
No Database file found: library/database.p
add video: H:/mp3s/beatport/ to videos: 0
add directory with wav or mp3 files
H:/mp3s/beatport/11801077_Alone In The Dark_(Remastered Original Mix).mp3
H:/mp3s/beatport/12355_Spiral_(Original Mix).mp3
H:/mp3s/beatport/13098550_Just_Be_Good_To_Me_Original_Mix.mp3
H:/mp3s/beatport/13233407_After The Rain_(Extended Club Mix).mp3
H:/mp3s/beatport/13577515_Touch_Me_PAX___Rui_Da_Silva_Extended_Version.mp3
H:/mp3s/beatport/14269418_Children_Extended_Mix.mp3
H:/mp3s/beatport/14278711_Madagascar_Alex_M_O_R_P_H__Extended_Remix.mp3
H:/mp3s/beatport/14324348_Your_Love_feat__Jamie_Principle_Alan_Dixon__Love_Attack__Extended_Remix.mp3
H:/mp3s/beatport/14360239_Easier_Original_Mix.mp3
H:/mp3s/beatport/14409377_Everything_Everything_Cosmic_Gate_Extended_Remix.mp3
H:/mp3s/beatport/14436359_Alive_Extended_Mix.mp3
H:/mp3s/beatport/14900610_Blame_(Extended Mix).mp3
H:/mp3s/beatport/14987083_Tree of Life_(Extended Mix).mp3
H:/mp3s/beatport/15005223_Save You_(Cold Blue Extended Remix).mp3
H:/mp3s/beatport/15009994_Starlab_(Extended Mix).mp3
H:/mp3s/beatport/15030367_Keep Me Believing feat. Megan McDuffee_(Extended Mix).mp3
H:/mp3s/beatport/15062411_Shattered Sun_(Extended Mix).mp3
H:/mp3s/beatport/15129652_Another Song_(Extended Mix).mp3
H:/mp3s/beatport/287724_Always A Fool_(Club Mix).mp3
H:/mp3s/beatport/3099819_Beauty Hides In The Deep_(Joc Extended).mp3
H:/mp3s/beatport/3510866_Flaming June_(Paul Van Dyk Remix).mp3
H:/mp3s/beatport/4709353_El Nino_(Original Mix).mp3
H:/mp3s/beatport/4791254_Home feat. Discovery_(Original Mix).mp3
H:/mp3s/beatport/7327402_Proper_Education__Club_Mix__Club_Mix.mp3
H:/mp3s/beatport/8095473_Amber_(Extended Mix).mp3
H:/mp3s/beatport/88564_Amsterdam_(Original Mix).mp3
H:/mp3s/beatport/Alive_(Extended_Mix).mp3
H:/mp3s/beatport/All_Around_The_World_(La_La_La)_(Extended_Version).mp3
H:/mp3s/beatport/Always_Be_My_Friend_(Extended_Mix).mp3
H:/mp3s/beatport/Another_Song_(Extended_Mix).mp3
H:/mp3s/beatport/A_Sky_Full_of_Stars_(Hardwell_Remix).mp3
H:/mp3s/beatport/Bittersweet_Symphony_(feat._Emily_Roberts)_(Extended_Version).mp3
H:/mp3s/beatport/Blame_(Extended_Mix).mp3
H:/mp3s/beatport/Can't_Hold_My_Tongue_(Original_Mix).mp3
H:/mp3s/beatport/Chain_My_Heart_(Extended_Mix).mp3
H:/mp3s/beatport/Children_(Extended_Mix).mp3
H:/mp3s/beatport/Come_2_Life_(Original_Mix).mp3
H:/mp3s/beatport/Divine_Love_(Original_Mix).mp3
H:/mp3s/beatport/Don't_Worry_(feat._Aloe_Blacc)_(Otsem_Extended_Mix).mp3
H:/mp3s/beatport/Don't_You_Want_Me_(Extended_Mix).mp3
H:/mp3s/beatport/Easier_((Extended_Mix)).mp3
H:/mp3s/beatport/Echoes_(Extended_Mix).mp3
H:/mp3s/beatport/El_Nino_(Original_Mix).mp3
H:/mp3s/beatport/Everything_Everything_(Cosmic_Gate_Extended_Remix).mp3
H:/mp3s/beatport/Feeling_Kinda_Strange_(Extended_Mix).mp3
H:/mp3s/beatport/Fix_you_(BSNO_Remix).mp3
H:/mp3s/beatport/Flaming_June_(Paul_Van_Dyk_Remix).mp3
H:/mp3s/beatport/Ghost_(Hausman_Extended_Remix).mp3
H:/mp3s/beatport/Giant_(Purple_Disco_Machine_Extended_Remix).mp3
H:/mp3s/beatport/Hearts_In_Darkness_(Original_Mix).mp3
H:/mp3s/beatport/Heaven_(David_Guetta_&_MORTEN_Tribute_Remix).mp3
H:/mp3s/beatport/Hide_U_(Tinlicker_Extended_Remix).mp3
H:/mp3s/beatport/Hooked_(Extended).mp3
H:/mp3s/beatport/Impossible_(feat._John_Martin)_(Extended_Mix).mp3
H:/mp3s/beatport/It's_A_Lot_(Extended).mp3
H:/mp3s/beatport/Just_Be_Good_To_Me_(Original_Mix).mp3
H:/mp3s/beatport/Keep_Me_Believing_feat._Megan_McDuffee_(Extended_Mix).mp3
H:/mp3s/beatport/Lose_Your_Head_(CamelPhat_Extended_Remix).mp3
H:/mp3s/beatport/Love_You_Better_feat._Kimberly_Fransens_(Original_Mix).mp3
H:/mp3s/beatport/Madagascar_(Alex_M.O.R.P.H._Extended_Remix).mp3
H:/mp3s/beatport/Move_Your_Body_(Extended_Mix).mp3
H:/mp3s/beatport/New_Vibe_Who_Dis_(feat._Little_League)_(Extended_Mix).mp3
H:/mp3s/beatport/Not_In_Love_(Extended).mp3
H:/mp3s/beatport/Out_Of_Reach_(Club_Mix).mp3
H:/mp3s/beatport/Paradise_(Fedde_Le_Grand_Remix).mp3
H:/mp3s/beatport/Paradise_(with_Sam_Feldt)_(Extended_Mix).mp3
H:/mp3s/beatport/Piece_Of_Your_Heart_(Alok_Extended_Remix).mp3
H:/mp3s/beatport/Pour_The_Milk_(Extended_Mix).mp3
H:/mp3s/beatport/Rasputin_(Extended_Mix).mp3
H:/mp3s/beatport/Rhythm_Of_The_Night_(Original_Extended_Mix).mp3
H:/mp3s/beatport/Save_You_(Cold_Blue_Extended_Remix).mp3
H:/mp3s/beatport/Shattered_Sun_(Extended_Mix).mp3
H:/mp3s/beatport/Shine_(Extended_Mix).mp3
H:/mp3s/beatport/Somebody_To_Love_(LIZOT_Extended_Remix).mp3
H:/mp3s/beatport/Starlab_(Extended_Mix).mp3
H:/mp3s/beatport/Sweet_Dreams_(Extended_Mix).mp3
H:/mp3s/beatport/Tell_Me_Why_(Jolyon_Petch_Remix).mp3
H:/mp3s/beatport/Touch_Me_(PAX_&_Rui_Da_Silva_Extended_Version).mp3
H:/mp3s/beatport/Tree_of_Life_(Extended_Mix).mp3
H:/mp3s/beatport/Turn_Me_On_(Extended).mp3
H:/mp3s/beatport/We_Got_That_Cool_(feat._Afrojack_&_Icona_Pop)_(Extended_Mix).mp3
H:/mp3s/beatport/You're_Not_Alone_(Extended_Mix).mp3
H:/mp3s/beatport/Young_&_Beautiful_(Cedric_Gervais_Remix).mp3
H:/mp3s/beatport/Your_Love_feat._Jamie_Principle_(Alan_Dixon_'Love_Attack'_Remix).mp3
H:/mp3s/beatport/You_Got_The_Love_(Extended_Mix).mp3
Found 85 wav or mp3 files
------ process audio H:/mp3s/beatport/11801077_Alone In The Dark_(Remastered Original Mix).mp3
converting mp3 to wav: H:/mp3s/beatport/11801077_Alone In The Dark_(Remastered Original Mix).mp3
C:\Python310\lib\site-packages\librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 164, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 195, in __soundfile_load
    main()
  File "F:\OneDrive\Documents\Github\polymath\polymath.py", line 611, in main
    videos = audio_directory_process(vids,videos)
  File "F:\OneDrive\Documents\Github\polymath\polymath.py", line 127, in audio_directory_process
    videos = audio_process(filesToProcess, videos)
  File "F:\OneDrive\Documents\Github\polymath\polymath.py", line 154, in audio_process
    y, sr = librosa.load(path=vid, sr=None, mono=False)
  File "C:\Python310\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 170, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Python310\lib\site-packages\librosa\core\audio.py", line 226, in __audioread_load
    reader = audioread.audio_open(path)
  File "C:\Python310\lib\site-packages\audioread\__init__.py", line 132, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError
```

**Comment by jimmyeao** [comment]
Nevermind, stupidly I forgot to add ffmpeg to the path
